name: dart_for_angular
description: Dart For Angular
version: 0.0.1
environment:
  sdk: ">=2.0.0-dev.64.2 <3.0.0"
dependencies:
  angular: ^5.0.0-beta+2
dev_dependencies:
  angular_test: ^2.0.0-beta+2
  build_runner: ^0.9.2
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  pageloader: ^3.0.0-beta
  test: ^1.3.0
